vg_guestbook:
    resource: "@VGGuestbookBundle/Controller/"
    type:     annotation
    prefix:   /

vg_user:
    resource: "@VGUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
